generic-service:
  nameOverride: hmpps-domain-event-logger
  productId: DPS060

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-domain-event-logger
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: domain-event-logger-cert

  serviceAccountName: hmpps-domain-event-logger

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-domain-event-logger:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    domain-events-sqs-domain-event-logger:
      HMPPS_SQS_QUEUES_PRISONER_QUEUE_NAME: "sqs_queue_name"
    domain-events-sqs-domain-event-logger-dlq:
      HMPPS_SQS_QUEUES_PRISONER_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-domain-event-logger
  alertSeverity: syscon
  sqsAlertsTotalMessagesThreshold: 0
