---
# Per environment values which override defaults in hmpps-domain-event-logger/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: domain-event-logger-dev.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '22 6 * * 1-5' # Start at 6.22am UTC Monday-Friday
    shutdown: '54 21 * * 1-5' # Stop at 9.54pm UTC Monday-Friday

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_HMPPS_AUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
  sqsNumberAlertQueueNames:
    - "syscon-devs-dev-hmpps_domain_event_logger_queue"
    - "syscon-devs-dev-hmpps_domain_event_logger_dlq"
